export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_FAIL    = 'GET_WEATHER_FAIL';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const CLEAR_ERRORS        = 'CLEAR_ERRORS';
export const ADD_ERRORS          = 'ADD_ERRORS';
